name: Build and Deploy CI

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: micro-frontend-archive
          path: dist/
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: lacribeiro11
          password: ab3761cc-32c3-4f11-9574-69ba8ebab972

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: lacribeiro11/registersystem-rootconfig:latest
